spring:
  application:
    name: demo-agent
  ai:
    dashscope:
      api-key: sk-b9e400b4180d4ff099c614f3d29d8df2
      image:
        options:
          model: wanx2.1-t2i-turbo
          width: 512
          height: 512
          n: 1
      chat:
        options:
          model: qwen-flash
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-v2
      read-timeout: 12000000

server:
  port: 8080

# WebSocket 配置
websocket:
  port: 8081
  path: /ws/agent

logging:
  level:
    org.springframework.ai: DEBUG
    io.github.hoooosi.demo: DEBUG
