server:
  port: 80
#=======================================================================================================================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.31.3:5432/meeting?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: postgres
    password: 123456
  data:
    redis:
      host: 192.168.31.3
      port: 6379
      timeout: 5000
      password: redis
#=======================================================================================================================
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#=======================================================================================================================
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: 'io.github.hoooosi.meeting.controller'
knife4j:
  enable: true
  setting:
    language: zh_cn
#=======================================================================================================================
rocketmq:
  name-server: 192.168.31.3:9876
  producer:
    group: meeting-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
#=======================================================================================================================
minio:
  endpoint: http://192.168.31.3:9000
  access-key: minio
  secret-key: 12345678
  bucket-name: picture

