services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - './!docker/data/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: 123456
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - './!docker/config/redis.conf:/usr/local/etc/redis/redis.conf'
      - './!docker/data/redis:/data/redis'
    command: redis-server /usr/local/etc/redis/redis.conf

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - './!docker/data/minio/data:/data'
      - './!docker/data/minio/events:/tmp/minio-events'
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678

  rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocket-dashboard
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876

  namesrv:
    image: apache/rocketmq:5.3.2
    container_name: namesrv
    ports:
      - "9876:9876"
    volumes:
      - './!docker/data/namesrv/logs:/home/rocketmq/logs'
      - './!docker/data/namesrv/store:/home/rocketmq/store'
    command: sh mqnamesrv

  broker:
    image: apache/rocketmq:5.3.2
    container_name: broker
    user: root
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    volumes:
      - './!docker/data/broker/logs:/root/logs'
      - './!docker/data/broker/store:/root/store'
      - './!docker/config/broker.conf:/home/rocketmq/cfg/broker.conf'
    environment:
      - JAVA_OPTS=-server -Xms512m -Xmx512m -Xmn256m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m
    command: sh mqbroker -c /home/rocketmq/cfg/broker.conf
    restart: always
    depends_on:
      - namesrv